description: FIXME
engine: gotpl
keywords:
- openstack
- neutron
- keystone-endpoint-internal
name: neutron-create-keystone-endpoint-internal-job
sources:
- http://github.com/openstack
version: 0.6.0-1
